# Port of the API
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://db.uulnruqyffhfnqqqjasw.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=@Flamengo201981*
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize Schema and Seed Data automatically from resources
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# JWT Secret configurations
app.jwt.secret=5f4dcc3b5aa765d61d8327deb882cf99a82862d2952a233c6d6d6d4a515c5453
app.jwt.expiration-ms=86400000

# OpenAPI Swagger docs path
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
